services:
  lms_client:
    build:
      context: .
    container_name: lms_client
    restart: always
    ports:
      - "3000:80"
    environment:
      VITE_BASE_URI_API: "http://api.domain.com:8080/v1"
      VITE_BASE_STATIC_FILE: "http://api.domain.com:8080"